const platformData = {
  heroSlides: [
    {
      title: "面向输电巡检的视觉算法能力",
      text: "覆盖本体缺陷、通道异物、烟雾火情等高频场景，支持售前展示和在线验证。",
      image: "./效果图/轮播/聚焦电力场景的视觉算法.jfif",
    },
    {
      title: "输电线路与设备识别能力",
      text: "聚焦通道巡检、设备缺陷与异物隐患识别，满足电力业务对稳定性和效率的要求。",
      image: "./效果图/轮播/输电线路与设备识别能力.png",
    },
    {
      title: "在线推理测试与结果留存",
      text: "支持样本上传、检测结果展示、JSON/PDF 导出与用户历史留存。",
      image: "./效果图/轮播/在线推理测试与结果留存.JPG",
    },
  ],
  algorithms: [
    {
      id: "algo-1",
      name: "输电线路本体缺陷检测",
      subtitle: "输电巡检",
      category: "目标检测",
      industry: "输电巡检",
      scene: "本体缺陷检测",
      metric: "mAP 92.4%",
      stack: "YOLOv8",
      desc: "识别绝缘子、金具、螺栓、塔材等部件异常，适用于输电线路本体巡检场景。",
      businessDesc: "适用于输电线路本体缺陷识别与异常告警场景。",
      favorites: 128,
      tests: 640,
      badge: "热门推荐",
      featured: true,
      image: "./效果图/输电线路本体缺陷检测/1474349739174.jpg",
    },
    {
      id: "algo-2",
      name: "输电通道山火烟雾识别",
      subtitle: "应急监管",
      category: "多模态识别",
      industry: "应急监管",
      scene: "山火识别",
      metric: "Recall 90.8%",
      stack: "YOLOv11 + Qwen2.5-VL",
      desc: "适用于输电通道烟雾、火点和风险事件的早期识别与告警。",
      businessDesc: "面向山火烟雾预警与通道风险识别演示。",
      favorites: 96,
      tests: 420,
      badge: "测试活跃",
      featured: true,
      image: "./效果图/冀北侵物检测/101746736.jpg",
    },
    {
      id: "algo-3",
      name: "配网杆塔关键部件识别",
      subtitle: "配网巡检",
      category: "目标检测",
      industry: "配网巡检",
      scene: "杆塔关键部件",
      metric: "mAP 89.6%",
      stack: "YOLOv8n + ByteTrack",
      desc: "识别杆塔关键部件、导线、绝缘子及附属结构，支撑配网巡检标准化。",
      businessDesc: "适合配网关键部件识别与巡检定位场景。",
      favorites: 114,
      tests: 518,
      badge: "方案常用",
      featured: true,
      image: "./效果图/配网杆塔关键部件识别/杆塔.JPG",
    },
    {
      id: "algo-4",
      name: "光伏缺陷检测与定位",
      subtitle: "光伏巡检",
      category: "目标检测",
      industry: "光伏巡检",
      scene: "热斑检测",
      metric: "mAP 87.3%",
      stack: "YOLO11",
      desc: "识别热斑、组件缺失、接线异常等问题，适合光伏运维场景。",
      businessDesc: "面向光伏热斑检测与组件异常排查。",
      favorites: 86,
      tests: 372,
      badge: "重点场景",
      featured: true,
      image: "./效果图/光伏缺陷检测以及定位/DJI_20210801101641_0069_T.JPG",
    },
    {
      id: "algo-5",
      name: "现场安检识别",
      subtitle: "安全监管",
      category: "目标检测",
      industry: "安全监管",
      scene: "现场安检",
      metric: "Recall 93.1%",
      stack: "InfraVision",
      desc: "支持人员着装规范、作业安全要素与风险行为检测。",
      businessDesc: "适合现场安检与安全监管演示。",
      favorites: 67,
      tests: 205,
      badge: "监管常用",
      featured: false,
      image: "./效果图/海南安检/11.3-329.JPG",
    },
    {
      id: "algo-6",
      name: "输电通道侵物识别",
      subtitle: "输电巡检",
      category: "目标检测",
      industry: "输电巡检",
      scene: "通道隐患识别",
      metric: "mAP 88.2%",
      stack: "YOLOv8 + OCR",
      desc: "识别输电通道中的施工机械、车辆、吊臂等外部风险目标。",
      businessDesc: "适用于输电通道隐患识别与风险排查。",
      favorites: 58,
      tests: 188,
      badge: "巡检常用",
      featured: false,
      image: "./效果图/冀北侵物检测/101741749.jpg",
    },
    {
      id: "algo-7",
      name: "去雾增强处理",
      subtitle: "图像增强",
      category: "图像处理",
      industry: "环境治理",
      scene: "低能见度增强",
      metric: "PSNR 31.2",
      stack: "DehazeNet",
      desc: "对低能见度图像进行去雾与清晰度提升，适合前置增强。",
      businessDesc: "适用于复杂天气图像增强和后续识别前处理。",
      favorites: 34,
      tests: 116,
      badge: "组合推荐",
      featured: false,
      image: "./效果图/去雾处理/0099_0.9_0.16.jpg",
    },
    {
      id: "algo-8",
      name: "水体异常识别",
      subtitle: "环保治理",
      category: "语义分割",
      industry: "环保治理",
      scene: "水体异常检测",
      metric: "IoU 82.7%",
      stack: "SegFormer",
      desc: "识别水面异常区域、漂浮物与污染特征，适用于环保治理场景。",
      businessDesc: "适合水体异常识别与环境治理演示。",
      favorites: 29,
      tests: 96,
      badge: "场景扩展",
      featured: false,
      image: "./效果图/去雾处理/1400_2.png",
    },
    {
      id: "algo-9",
      name: "变电设备缺陷智能识别",
      subtitle: "变电巡检",
      category: "异常分析",
      industry: "变电巡检",
      scene: "设备状态识别",
      metric: "准确率 91.2%",
      stack: "孪生网络",
      desc: "分析设备状态变化与典型缺陷，适用于变电设备巡检与运维辅助。",
      businessDesc: "适用于设备状态识别与运维异常分析。",
      favorites: 41,
      tests: 132,
      badge: "运维关注",
      featured: false,
      image: "./效果图/变电设备缺陷智能识别/biandian_02102.jpg",
    },
  ],
  industries: [
    {
      name: "输电巡检",
      desc: "覆盖线路本体缺陷、通道异物、山火烟雾和隐患识别等高价值场景。",
      scenes: ["本体缺陷检测", "通道隐患识别", "山火预警"],
    },
    {
      name: "配网巡检",
      desc: "聚焦杆塔、关键部件和配网设备状态识别，支撑巡检业务数字化。",
      scenes: ["杆塔关键部件", "设备状态识别", "巡检定位"],
    },
    {
      name: "光伏巡检",
      desc: "面向热斑、组件缺陷和阵列异常场景，提升光伏运维效率。",
      scenes: ["热斑检测", "组件异常定位", "阵列识别"],
    },
    {
      name: "安全监管",
      desc: "面向现场安检、作业规范识别和安全风险提醒等监管类场景。",
      scenes: ["现场安检", "安全穿戴", "作业规范"],
    },
    {
      name: "应急监管",
      desc: "服务山火、烟雾和突发事件场景，强化快速识别和预警能力。",
      scenes: ["山火识别", "烟雾检测", "事件预警"],
    },
    {
      name: "环保治理",
      desc: "覆盖漂浮物、水体异常和图像增强等治理类场景。",
      scenes: ["漂浮物检测", "水体异常识别", "低能见度增强"],
    },
  ],
  resources: [
    { title: "平台能力清单", meta: "资料下载", type: "资料手册" },
    { title: "电力巡检算法目录", meta: "能力目录", type: "能力说明" },
    { title: "在线检测使用说明", meta: "操作指南", type: "使用手册" },
    { title: "合作接入方式", meta: "商务支持", type: "合作文档" },
    { title: "项目案例摘要", meta: "案例精选", type: "案例沉淀" },
    { title: "演示脚本模板", meta: "售前支持", type: "交付资料" },
  ],
  resourceHub: {
    featured: {
      title: "视觉算法平台能力总览",
      type: "重点资料",
      desc: "从平台定位、算法分类、在线检测、结果导出到合作推进，形成面向售前展示与项目沟通的总览入口。",
      highlights: ["平台能力地图", "在线检测流程", "导出与接入说明"],
      actionLabel: "查看总览",
      actionHref: "./resources.html",
    },
    groups: [
      {
        title: "方案资料",
        items: [
          { name: "输电巡检解决方案", meta: "适用于输电本体缺陷与通道隐患场景" },
          { name: "光伏缺陷检测方案", meta: "覆盖热斑检测、组件异常与定位流程" },
        ],
      },
      {
        title: "能力说明",
        items: [
          { name: "在线检测与结果导出指南", meta: "说明上传、检测、JSON/PDF 导出流程" },
          { name: "API 接入说明", meta: "适合系统对接与业务流程集成评估" },
        ],
      },
      {
        title: "项目案例",
        items: [
          { name: "典型案例：光伏缺陷检测", meta: "从问题发现到结果留存的完整案例摘要" },
          { name: "典型案例：安全监管识别", meta: "展示作业安全监管类项目的落地方式" },
        ],
      },
    ],
    actions: [
      { title: "算法商城", desc: "浏览算法分类、场景能力并进入在线检测与验证流程", href: "./market.html" },
      { title: "大模型能力", desc: "查看视觉理解、知识问答与多模态分析相关能力入口", href: "./llm.html" },
      { title: "合作咨询", desc: "查看商务合作、资料对接与项目推进相关联系方式", href: "#cooperation" },
    ],
  },
  llms: [
    {
      name: "电力巡检多模态大模型",
      type: "视觉理解 / 报告生成",
      desc: "面向巡检图像理解、缺陷归因和检测报告输出的多模态模型能力。",
      tags: ["图像理解", "问题归因", "报告生成"],
    },
    {
      name: "运维知识问答大模型",
      type: "知识增强 / 问答助手",
      desc: "结合设备知识库与项目资料，提供运维问答与辅助决策能力。",
      tags: ["RAG", "知识问答", "运维助手"],
    },
    {
      name: "多模态预警分析模型",
      type: "图文视频联合分析",
      desc: "融合图像、文本与传感信息，支撑复杂场景下的预警解释与事件联动。",
      tags: ["多模态", "预警分析", "事件联动"],
    },
  ],
};
