const platformData = {
  heroSlides: [
    {
      title: "面向电力巡检的视觉算法能力",
      text: "聚焦输电、配网与光伏场景，以可展示、可验证、可交付的方式组织算法能力。",
      image: "./效果图/轮播/聚焦电力场景的视觉算法.jfif",
    },
    {
      title: "输电线路与设备识别能力",
      text: "覆盖通道隐患、杆塔设备、缺陷识别等高频场景，服务巡检和运维业务。",
      image: "./效果图/轮播/输电线路与设备识别能力.png",
    },
    {
      title: "在线推理测试与结果留存",
      text: "支持样本上传、结果预览、指标输出与历史留存，缩短售前沟通与验证路径。",
      image: "./效果图/轮播/在线推理测试与结果留存.JPG",
    },
  ],
  algorithms: [
    {
      id: "algo-1",
      name: "输电线路本体缺陷检测",
      subtitle: "29 类输电本体缺陷识别",
      category: "目标检测",
      industry: "输电巡检",
      scene: "本体缺陷检测",
      metric: "mAP 92.4%",
      stack: "YOLOv8",
      desc: "识别异物、鸟巢、绝缘子缺陷、金具状态和螺栓松动等重点问题。",
      featured: true,
      image: "./效果图/输电线路本体缺陷检测/1474349739174.jpg",
    },
    {
      id: "algo-2",
      name: "输电通道山火烟雾识别",
      subtitle: "烟雾与火情双目标告警",
      category: "多模态识别",
      industry: "应急救援",
      scene: "山火识别",
      metric: "Recall 90.8%",
      stack: "YOLOv11 + Qwen2.5-VL",
      desc: "适合通道监测与预警场景，突出早期识别与多模态感知能力。",
      featured: true,
      image: "./效果图/冀北侵物检测/101746736.jpg",
    },
    {
      id: "algo-3",
      name: "配网杆塔关键部件识别",
      subtitle: "配网关键部件识别与跟踪",
      category: "目标检测",
      industry: "配网巡检",
      scene: "杆塔关键部件",
      metric: "mAP 89.6%",
      stack: "YOLOv8n + ByteTrack",
      desc: "识别塔头、导线、刀闸、断路器和熔断器等关键部件。",
      featured: true,
      image: "./效果图/配网杆塔关键部件识别/10kV-wang-qiao-08-xian-104#-quan-ta.JPG",
    },
    {
      id: "algo-4",
      name: "光伏缺陷检测与定位",
      subtitle: "热斑与组件缺陷识别",
      category: "目标检测",
      industry: "光伏巡检",
      scene: "热斑检测",
      metric: "mAP 87.3%",
      stack: "YOLO11",
      desc: "识别热斑、接线故障和组件缺失等问题，适合光伏运维展示。",
      featured: true,
      image: "./效果图/光伏缺陷检测以及定位/DJI_20210801101641_0069_T.JPG",
    },
    {
      id: "algo-5",
      name: "现场安检识别",
      subtitle: "作业现场安全规范识别",
      category: "目标检测",
      industry: "安全监管",
      scene: "现场安检",
      metric: "Recall 93.1%",
      stack: "InfraVision",
      desc: "适用于现场人员规范识别、安全要素检测与异常告警。",
      featured: false,
      image: "./效果图/海南安检/11.3-329.JPG",
    },
    {
      id: "algo-6",
      name: "输电通道侵物识别",
      subtitle: "通道异物与风险目标监测",
      category: "目标检测",
      industry: "输电巡检",
      scene: "通道隐患识别",
      metric: "mAP 88.2%",
      stack: "YOLOv8 + OCR",
      desc: "识别通道中的外部风险目标，适合输电巡检业务展示。",
      featured: false,
      image: "./效果图/冀北侵物检测/101741749.jpg",
    },
    {
      id: "algo-7",
      name: "水面漂浮物检测",
      subtitle: "环保巡查中的漂浮物识别",
      category: "目标检测",
      industry: "环保治理",
      scene: "漂浮物检测",
      metric: "mAP 86.4%",
      stack: "YOLOv8",
      desc: "识别漂浮垃圾、障碍物和污染相关目标，适合治理场景演示。",
      featured: false,
      image: "./效果图/去雾处理/0099_0.9_0.16.jpg",
    },
    {
      id: "algo-8",
      name: "水体异常识别",
      subtitle: "水域分割与异常特征识别",
      category: "语义分割",
      industry: "环保治理",
      scene: "水体异常识别",
      metric: "IoU 82.7%",
      stack: "SegFormer",
      desc: "适合环境治理和遥感监测类场景展示。",
      featured: false,
      image: "./效果图/去雾处理/1400_2.png",
    },
    {
      id: "algo-9",
      name: "变电设备缺陷识别",
      subtitle: "变电设备状态与缺陷分析",
      category: "异常分析",
      industry: "配网巡检",
      scene: "设备状态识别",
      metric: "准确率 91.2%",
      stack: "孪生网络",
      desc: "分析设备状态变化和典型缺陷，适合运维场景能力展示。",
      featured: false,
      image: "./效果图/变电设备缺陷智能识别/biandian_02102.jpg",
    },
  ],
  industries: [
    {
      name: "输电巡检",
      desc: "聚焦线路缺陷、通道异物、山火烟雾和设备识别等高价值场景。",
      scenes: ["本体缺陷检测", "通道隐患识别", "山火预警"],
    },
    {
      name: "配网巡检",
      desc: "覆盖杆塔、关键部件、设备状态与配网通道场景，适合巡检与运维业务。",
      scenes: ["杆塔关键部件", "设备状态识别", "通道巡检"],
    },
    {
      name: "光伏巡检",
      desc: "面向热斑、组件缺陷和阵列异常定位，强化光伏运维场景价值表达。",
      scenes: ["热斑检测", "组件缺陷定位", "阵列异常识别"],
    },
    {
      name: "安全监管",
      desc: "支撑安全帽穿戴、现场安检与作业规范识别等监管类应用。",
      scenes: ["作业规范识别", "安全帽检测", "现场安检"],
    },
    {
      name: "应急救援",
      desc: "服务山火、烟雾和灾害应急识别场景，强调快速预警与多模态识别能力。",
      scenes: ["山火识别", "烟雾检测", "灾害搜救"],
    },
    {
      name: "环保治理",
      desc: "覆盖漂浮物、水体异常和环境目标识别等治理类场景。",
      scenes: ["漂浮物检测", "水体异常识别", "环境巡查"],
    },
  ],
  resources: [
    { title: "平台能力清单", meta: "资料下载", type: "资料手册" },
    { title: "电力巡检算法目录", meta: "能力目录", type: "能力说明" },
    { title: "在线测试说明", meta: "使用指南", type: "操作指南" },
    { title: "合作接入方式", meta: "商务支持", type: "合作文档" },
    { title: "项目案例摘要", meta: "案例精选", type: "案例沉淀" },
    { title: "演示脚本模板", meta: "售前支撑", type: "演示资料" },
  ],
  llms: [
    {
      name: "电力巡检多模态大模型",
      type: "视觉理解 / 报告生成",
      desc: "面向巡检图像理解、缺陷归因、风险摘要与报告输出的业务模型能力。",
      tags: ["图像理解", "问题归因", "报告生成"],
    },
    {
      name: "运维知识问答大模型",
      type: "知识增强 / 交互问答",
      desc: "结合电力设备知识库与项目文档，提供面向业务人员的问答与辅助决策能力。",
      tags: ["RAG", "知识问答", "运维辅助"],
    },
    {
      name: "多模态预警分析模型",
      type: "图文视频联合分析",
      desc: "融合图像、文本与传感信息，支撑复杂场景下的预警解释与事件联动。",
      tags: ["多模态", "预警分析", "事件联动"],
    },
  ],
};
